In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Visualizando os dados

In [2]:


caminho_bruto = Path('../dados/bruto')
arquivos_csv = list(caminho_bruto.glob('*.csv'))

dfs = []
colunas_padrao = None
estruturas_compativeis = True

for arquivo in arquivos_csv:
    
    df = pd.read_csv(arquivo, sep=';') 
    

    print(f"\nArquivo: {arquivo.name} | Formato: {df.shape[0]} linhas, {df.shape[1]} colunas")
    display(df.head(2))
    
    
    colunas_atuais = list(df.columns)
    if colunas_padrao is None:
        colunas_padrao = colunas_atuais
    elif colunas_padrao != colunas_atuais:
        estruturas_compativeis = False
        print(f"⚠️ Inconsistência encontrada no arquivo: {arquivo.name}")
        
    dfs.append(df)


if not arquivos_csv:
    print("Nenhum arquivo CSV encontrado na pasta especificada.")
elif estruturas_compativeis:
    print("\n Estruturas verificadas e idênticas. Unindo os arquivos...")
    df_unificado = pd.concat(dfs, ignore_index=True)
    
    print(f"DataFrame final criado com sucesso! Formato unificado: {df_unificado.shape}")
    display(df_unificado.head())
    
    
else:
    print("\n Os arquivos possuem estruturas de colunas diferentes. A junção automática foi abortada para preservar a integridade.")

Arquivo: Preços semestrais - AUTOMOTIVOS_2024.01.csv | Formato: 477154 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA

Arquivo: Preços semestrais - AUTOMOTIVOS_2024.02.csv | Formato: 421382 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA,01/07/2024,"6,79",NaN,R$ / litro,VIBRA
1,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA ADITIVADA,01/07/2024,"6,84",NaN,R$ / litro,VIBRA

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7860\2043983574.py:10: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 14: Unidade de Medida, 15: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(arquivo, sep=';')

Arquivo: Preços semestrais - AUTOMOTIVOS_2025.01.csv | Formato: 429523 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN

Arquivo: Preços semestrais - AUTOMOTIVOS_2025.02.csv | Formato: 384208 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA

Arquivo: Preços semestrais - AUTOMOTIVOS_2026.01.csv | Formato: 422418 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,GASOLINA,02/01/2026,"7,97",NaN,R$ / litro,IPIRANGA
1,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,DIESEL,02/01/2026,"8,15",NaN,R$ / litro,IPIRANGA

 Estruturas verificadas e idênticas. Unindo os arquivos...
DataFrame final criado com sucesso! Formato unificado: (2134685, 16)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,"5,93",NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,"3,99",NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,"5,48",NaN,R$ / litro,VIBRA

In [3]:



linhas, colunas = df_unificado.shape
linhas_duplicadas = df_unificado.duplicated().sum()

print("="*50)
print("🔍 INSPEÇÃO GERAL DO DATASET")
print("="*50)
print(f"Dimensões globais : {linhas} linhas e {colunas} colunas")
print(f"Linhas duplicadas : {linhas_duplicadas} ocorrencias exatas")
print("="*50 + "\n")


inspecao = pd.DataFrame({
    'Tipo': df_unificado.dtypes,
    'Ausências (Qtd)': df_unificado.isnull().sum(),
    'Ausências (%)': (df_unificado.isnull().sum() / linhas) * 100,
    'Chaves/Únicos': df_unificado.nunique()
})

amostras = []
for col in df_unificado.columns:
    valores = df_unificado[col].dropna().unique()
    amostra_str = ", ".join(map(str, valores[:3]))
    if len(valores) > 3:
        amostra_str += ", ..."
    amostras.append(amostra_str)

inspecao['Categorias (Amostras)'] = amostras

inspecao['Ausências (%)'] = inspecao['Ausências (%)'].round(2).astype(str) + '%'

inspecao = inspecao.sort_values(by='Ausências (Qtd)', ascending=False)

display(inspecao)

==================================================
🔍 INSPEÇÃO GERAL DO DATASET
==================================================
Dimensões globais : 2134685 linhas e 16 colunas
Linhas duplicadas : 9129 ocorrencias exatas
==================================================

,Tipo,Ausências (Qtd),Ausências (%),Chaves/Únicos,Categorias (Amostras)
Valor de Compra,float64,2134685,100.0%,0,
Complemento,str,1649676,77.28%,2362,"KM 70, LOTE 12 QUADRAB, L..."
Bairro,str,12807,0.6%,5511,"SANTA ESMERALDA, CENTRO, CANAFISTULA, ..."
Numero Rua,str,9367,0.44%,4158,"1901, 274, 678, ..."
Revenda,str,9114,0.43%,11558,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...
Municipio,str,9114,0.43%,461,"ARAPIRACA, RIO LARGO, VERA CRUZ, ..."
Regiao - Sigla,str,9114,0.43%,5,"NE, SE, S, ..."
Estado - Sigla,str,9114,0.43%,27,"AL, BA, MA, ..."
CNPJ da Revenda,object,9114,0.43%,20767,"02.817.655/0001-82, 12.706.529/0001-04, 01...."
Nome da Rua,str,9114,0.43%,8189,"RODOVIA AL-220, RUA SAO FRANCISCO, RODOVIA AL-..."
Produto,str,9114,0.43%,6,"GASOLINA, GASOLINA ADITIVADA, DIESEL S10, ..."
Cep,str,9114,0.43%,9862,"57312-025, 57300-080, 57302-802, ..."
Data da Coleta,str,9114,0.43%,680,"01/01/2024, 02/01/2024, 03/01/2024, ..."
Valor de Venda,str,9114,0.43%,704,"5,68, 5,93, 3,99, ..."
Unidade de Medida,str,9114,0.43%,3,"R$ / litro, R$ / m³, R$ / m3"
Bandeira,str,9114,0.43%,55,"VIBRA, BRANCA, IPIRANGA, ..."

# **Limpeza e Normalização dos Dados (Limpar)**

   Nesta etapa, foram realizados ajustes na base de dados unificada, com foco na correção de inconsistências, padronização das informações e tratamento de valores ausentes.

**Padronização dos Nomes das Colunas:**

   Os nomes das colunas foram convertidos para o padrão snake_case, utilizando letras minúsculas e substituindo espaços e hífens por underscores (_). Essa alteração manteve a nomenclatura uniforme em toda a base.

**Remoção de Duplicidades:**

   Foram removidos os registros completamente duplicados, identificados durante a inspeção inicial dos dados, evitando a repetição de informações nas análises.

**Tratamento de Identificadores e Valores Monetários:**

   Na coluna valor_de_venda, foi realizada a substituição da vírgula pelo ponto como separador decimal, seguida da conversão dos valores para o tipo numérico float64.
   Já nas colunas cnpj_da_revenda e cep, foram removidos caracteres especiais, como pontos, barras e hífens, mantendo apenas os dígitos dos identificadores.

**Padronização de Categorias e Unidades de Medida:**

   Na coluna unidade_de_medida, foram corrigidas diferenças de escrita, como a substituição de m3 por m³.
   Além disso, os valores das colunas de texto foram convertidos para letras minúsculas, mantendo um padrão único para os registros categóricos.

**Tratamento de Datas:**

   A coluna data_da_coleta foi convertida para o formato de data, retirando a exibição do horário (00:00:00). Os registros sem informação de data foram mantidos como NaT, preservando a identificação dos valores ausentes.
   
**Tratamento de Valores Ausentes:**

   Os valores ausentes da coluna numérica valor_de_compra foram preenchidos com 0. Para as colunas de texto, os registros nulos foram substituídos pela expressão "não consta", permitindo identificar as informações que não estavam disponíveis na base.

In [4]:
df_unificado.columns = (
    df_unificado.columns
    .str.lower()
    .str.replace(' - ', '_')
    .str.replace(' ', '_')
)

df_unificado = df_unificado.drop_duplicates()

if 'valor_de_venda' in df_unificado.columns:
    df_unificado['valor_de_venda'] = df_unificado['valor_de_venda'].astype(str).str.replace(',', '.')
    df_unificado['valor_de_venda'] = pd.to_numeric(df_unificado['valor_de_venda'], errors='coerce')

if 'cnpj_da_revenda' in df_unificado.columns:
    df_unificado['cnpj_da_revenda'] = df_unificado['cnpj_da_revenda'].astype(str).str.replace(r'\D', '', regex=True)
    df_unificado['cnpj_da_revenda'] = df_unificado['cnpj_da_revenda'].replace(['nan', ''], np.nan)

if 'cep' in df_unificado.columns:
    df_unificado['cep'] = df_unificado['cep'].astype(str).str.replace(r'\D', '', regex=True)
    df_unificado['cep'] = df_unificado['cep'].replace(['nan', ''], np.nan)

if 'unidade_de_medida' in df_unificado.columns:
    df_unificado['unidade_de_medida'] = (
        df_unificado['unidade_de_medida']
        .astype(str)
        .str.replace('m3', 'm³')
        .replace('nan', np.nan)
    )

if 'data_da_coleta' in df_unificado.columns:
    df_unificado['data_da_coleta'] = pd.to_datetime(df_unificado['data_da_coleta'], format='%d/%m/%Y', errors='coerce')
    df_unificado['data_da_coleta'] = df_unificado['data_da_coleta'].dt.date

colunas_numericas = df_unificado.select_dtypes(include=['float64', 'int64']).columns
colunas_texto = df_unificado.select_dtypes(include=['object', 'string']).columns

df_unificado[colunas_numericas] = df_unificado[colunas_numericas].fillna(0)

for col in colunas_texto:
    if col == 'data_da_coleta':
        continue
        
    df_unificado[col] = df_unificado[col].fillna("não consta")
    df_unificado[col] = df_unificado[col].astype(str).str.lower()

print(" Limpeza concluída: datas, textos em minúsculas e CEP tratados!")
print(f"Novas dimensões após limpeza: {df_unificado.shape[0]} linhas e {df_unificado.shape[1]} colunas")
display(df_unificado.head())

 Limpeza concluída: datas, textos em minúsculas e CEP tratados!
Novas dimensões após limpeza: 2125556 linhas e 16 colunas

,regiao_sigla,estado_sigla,municipio,revenda,cnpj_da_revenda,nome_da_rua,numero_rua,complemento,bairro,cep,produto,data_da_coleta,valor_de_venda,valor_de_compra,unidade_de_medida,bandeira
0,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,gasolina,2024-01-01,5.68,0.0,r$ / litro,vibra
1,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,gasolina aditivada,2024-01-01,5.68,0.0,r$ / litro,vibra
2,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,diesel s10,2024-01-01,5.93,0.0,r$ / litro,vibra
3,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,etanol,2024-01-01,3.99,0.0,r$ / litro,vibra
4,ne,al,arapiraca,auto posto sao francisco ltda,12706529000104,rua sao francisco,274,não consta,centro,57300080,gasolina,2024-01-01,5.48,0.0,r$ / litro,vibra

# 5. Transformação dos Dados (Transformar)

    Nesta etapa, foram realizadas transformações na base de dados para facilitar as análises e permitir uma melhor organização das informações. Além dos ajustes de consistência, foram criadas novas variáveis e uma visão agregada dos dados.

    Filtragem de Consistência

    Foram removidos os registros que apresentavam valores de venda iguais ou inferiores a zero, considerando que esses valores poderiam representar inconsistências na coleta e comprometer os resultados das análises estatísticas.

    Criação das Variáveis ano_coleta e mes_coleta

    A partir da data de coleta, foram extraídos o ano e o mês de cada registro. Essa separação permite acompanhar as variações dos preços ao longo do tempo, facilitando a identificação de padrões e possíveis comportamentos sazonais.

    Criação da Variável tipo_bandeira

    Os postos foram classificados em duas categorias: independente, para postos de bandeira branca, e rede_franqueada, para os demais. Essa divisão permite comparar os preços praticados pelos diferentes tipos de estabelecimento e identificar possíveis diferenças entre eles.

    Criação da Variável faixa_de_preco

    Os valores de venda foram agrupados em três categorias: baixo, médio e alto, utilizando os quartis como referência. Essa classificação facilita a comparação entre diferentes regiões e a identificação de locais com maior concentração de preços elevados ou reduzidos.

Criação da Visão Agregada (Resumo Estatístico)

Foi criada uma base resumida com o agrupamento dos dados por estado e produto, considerando a média, mediana, valores máximo e mínimo dos preços de venda, além da quantidade de revendas distintas (quantidade_revendas_distintas).

Como a base original possui mais de 2 milhões de registros, essa agregação permite realizar consultas de forma mais prática, reduzindo a necessidade de processar todos os registros em cada análise. Além disso, a estrutura facilita a construção de visualizações e dashboards no Power BI.

In [5]:
df_transformado = df_unificado.copy()

df_transformado = df_transformado[df_transformado['valor_de_venda'] > 0]

datas_datetime = pd.to_datetime(df_transformado['data_da_coleta'], errors='coerce')
df_transformado['ano_coleta'] = datas_datetime.dt.year
df_transformado['mes_coleta'] = datas_datetime.dt.month

df_transformado['tipo_bandeira'] = np.where(
    df_transformado['bandeira'] == 'branca', 
    'independente', 
    'rede_franqueada'
)

df_transformado['faixa_de_preco'] = pd.qcut(
    df_transformado['valor_de_venda'], 
    q=3, 
    labels=['baixo', 'médio', 'alto'], 
    duplicates='drop'
)

df_agregado = (
    df_transformado
    .groupby(['estado_sigla', 'produto'])
    .agg(
        preco_medio=('valor_de_venda', 'mean'),
        preco_mediano=('valor_de_venda', 'median'),
        preco_maximo=('valor_de_venda', 'max'),
        preco_minimo=('valor_de_venda', 'min'),
        quantidade_revendas_distintas=('cnpj_da_revenda', 'nunique')
    )
    .reset_index()
)

colunas_moeda = ['preco_medio', 'preco_mediano', 'preco_maximo', 'preco_minimo']
df_agregado[colunas_moeda] = df_agregado[colunas_moeda].round(2)

print("Transformações aplicadas com sucesso!")
print(f"Dimensões do dataset principal transformado: {df_transformado.shape}")
print("\n Amostra das novas variáveis derivadas ")
display(df_transformado[['data_da_coleta', 'ano_coleta', 'mes_coleta', 'bandeira', 'tipo_bandeira', 'valor_de_venda', 'faixa_de_preco']].head())

print("\n Visão Agregada (Média de Preços por Estado e Produto) ")
display(df_agregado.head())

caminho_salvamento = Path('../dados/processado/base_anp_transformada.csv')

caminho_salvamento.parent.mkdir(parents=True, exist_ok=True)

df_transformado.to_csv(caminho_salvamento, index=False, sep=',')

print(f" Arquivo salvo com sucesso em: {caminho_salvamento}")

Transformações aplicadas com sucesso!
Dimensões do dataset principal transformado: (2125555, 20)

 Amostra das novas variáveis derivadas

,data_da_coleta,ano_coleta,mes_coleta,bandeira,tipo_bandeira,valor_de_venda,faixa_de_preco
0,2024-01-01,2024,1,vibra,rede_franqueada,5.68,baixo
1,2024-01-01,2024,1,vibra,rede_franqueada,5.68,baixo
2,2024-01-01,2024,1,vibra,rede_franqueada,5.93,médio
3,2024-01-01,2024,1,vibra,rede_franqueada,3.99,baixo
4,2024-01-01,2024,1,vibra,rede_franqueada,5.48,baixo

 Visão Agregada (Média de Preços por Estado e Produto)

,estado_sigla,produto,preco_medio,preco_mediano,preco_maximo,preco_minimo,quantidade_revendas_distintas
0,ac,diesel,7.58,7.55,8.77,6.79,47
1,ac,diesel s10,7.64,7.65,9.27,6.89,46
2,ac,etanol,5.24,5.24,7.44,4.49,32
3,ac,gasolina,7.39,7.39,8.50,6.49,51
4,ac,gasolina aditivada,7.44,7.45,8.59,6.51,47

 Arquivo salvo com sucesso em: ..\dados\processado\base_anp_transformada.csv

In [10]:
# Estatísticas descritivas por região e combustível
estatisticas_regiao = (
    df_transformado
    .groupby(['regiao_sigla', 'produto'])
    .agg(
        quantidade=('valor_de_venda', 'count'),
        preco_medio=('valor_de_venda', 'mean'),
        mediana=('valor_de_venda', 'median'),
        minimo=('valor_de_venda', 'min'),
        maximo=('valor_de_venda', 'max'),
        desvio_padrao=('valor_de_venda', 'std')
    )
    .round(2)
    .reset_index()
)

display(estatisticas_regiao)

,regiao_sigla,produto,quantidade,preco_medio,mediana,minimo,maximo,desvio_padrao
0,co,diesel,23647,6.15,5.99,5.19,8.89,0.51
1,co,diesel s10,28665,6.23,6.09,5.18,8.91,0.52
2,co,etanol,38733,4.17,4.09,2.67,5.89,0.48
3,co,gasolina,45034,6.19,6.19,4.79,7.55,0.39
4,co,gasolina aditivada,29633,6.35,6.39,4.85,8.99,0.41
5,co,gnv,368,4.26,4.09,3.54,6.69,0.51
6,n,diesel,21559,6.62,6.49,4.69,8.77,0.59
7,n,diesel s10,29604,6.61,6.49,4.99,9.29,0.66
8,n,etanol,20174,4.94,4.99,3.39,7.44,0.50
9,n,gasolina,39319,6.61,6.62,4.74,9.29,0.60
10,n,gasolina aditivada,28456,6.80,6.88,4.79,9.29,0.55
11,n,gnv,218,4.79,4.99,3.99,5.49,0.51
12,ne,diesel,38685,6.23,6.09,5.09,9.45,0.61
13,ne,diesel s10,85324,6.22,6.04,4.73,9.55,0.59
14,ne,etanol,92773,4.76,4.75,3.09,6.94,0.47
15,ne,gasolina,110793,6.27,6.26,4.75,8.88,0.48
16,ne,gasolina aditivada,83119,6.41,6.39,4.88,8.99,0.47
17,ne,gnv,9825,4.72,4.69,3.69,6.28,0.39
18,s,diesel,49149,6.15,6.07,5.04,8.84,0.46
19,s,diesel s10,68162,6.25,6.14,5.09,8.99,0.49
20,s,etanol,65006,4.52,4.51,2.99,6.99,0.47
21,s,gasolina,96339,6.23,6.25,4.99,9.08,0.37
22,s,gasolina aditivada,86686,6.39,6.39,5.03,9.79,0.39
23,s,gnv,6251,4.88,4.89,3.99,6.14,0.29
24,se,diesel,101324,6.12,5.99,5.09,8.99,0.50
25,se,diesel s10,176170,6.24,6.09,4.99,9.99,0.55
26,se,etanol,252264,4.12,4.09,2.63,6.59,0.48
27,se,gasolina,264877,6.05,5.99,4.55,9.79,0.45
28,se,gasolina aditivada,204442,6.30,6.29,4.69,9.89,0.50
29,se,gnv,28956,4.68,4.59,3.28,6.89,0.50

**Particionamento dos Dados (Particionar)**

  A base de dados foi dividida em três subconjuntos: treino, validação e teste, seguindo uma ordem cronológica para preservar a sequência temporal dos registros.

  Para isso, os dados foram organizados pela data de coleta e divididos sequencialmente, sem a utilização de embaralhamento aleatório (shuffle=False). A distribuição foi realizada da seguinte forma:

**Treino (70%)**

  Composto por 1.487.888 registros, abrangendo o período de 01/01/2024 a 24/09/2025. Esse conjunto foi destinado ao treinamento do modelo, utilizando os dados do período mais antigo.

**Validação (15%)**

  Composto por 318.833 registros, correspondentes ao período de 24/09/2025 a 16/02/2026. Essa parcela foi reservada para acompanhar o desempenho do modelo durante o desenvolvimento e realizar os ajustes necessários nos hiperparâmetros.

**Teste (15%)**

  Composto por 318.834 registros, abrangendo o período de 16/02/2026 a 30/06/2026. Esse conjunto foi reservado para a avaliação final do modelo, utilizando os registros mais recentes da base.

**Justificativa do Particionamento**

  A divisão cronológica foi adotada considerando as variações dos preços dos combustíveis ao longo do tempo. Um particionamento aleatório poderia misturar informações de diferentes períodos, permitindo que dados mais recentes influenciassem o treinamento destinado a prever períodos anteriores.

  Dessa forma, a separação temporal reduz o risco de vazamento de dados (Data Leakage) e permite avaliar o desempenho do modelo em períodos posteriores aos utilizados no treinamento.

  Além disso, a divisão mantém os dados de teste separados das etapas de treinamento e validação, possibilitando uma avaliação mais adequada da capacidade de generalização do modelo.

In [6]:
df_modelagem = df_transformado.sort_values(by='data_da_coleta').reset_index(drop=True)

X = df_modelagem.drop(columns=['valor_de_venda'])
y = df_modelagem['valor_de_venda']


X_treino, X_temp, y_treino, y_temp = train_test_split(
    X, y, 
    test_size=0.30, 
    shuffle=False 
)

X_val, X_teste, y_val, y_teste = train_test_split(
    X_temp, y_temp, 
    test_size=0.50, 
    shuffle=False
)

print("Particionamento cronológico concluído com sucesso!")
print(f"Treino (70%)    : {X_treino.shape[0]} linhas")
print(f"Validação (15%) : {X_val.shape[0]} linhas")
print(f"Teste (15%)     : {X_teste.shape[0]} linhas")

print("\n--- Verificação Temporal ---")
print(f"Treino    : de {X_treino['data_da_coleta'].min()} até {X_treino['data_da_coleta'].max()}")
print(f"Validação : de {X_val['data_da_coleta'].min()} até {X_val['data_da_coleta'].max()}")
print(f"Teste     : de {X_teste['data_da_coleta'].min()} até {X_teste['data_da_coleta'].max()}")

Particionamento cronológico concluído com sucesso!
Treino (70%)    : 1487888 linhas
Validação (15%) : 318833 linhas
Teste (15%)     : 318834 linhas

--- Verificação Temporal ---
Treino    : de 2024-01-01 até 2025-09-24
Validação : de 2025-09-24 até 2026-02-16
Teste     : de 2026-02-16 até 2026-06-30

 **Referenciar (`Baseline e Métrica Inicial`)**

   Nesta etapa, foi estabelecida a baseline do projeto, utilizando um modelo de referência para comparar o desempenho dos modelos preditivos que serão desenvolvidos posteriormente.

**Construção do Modelo de Referência (Dummy Regressor)**

   Foi utilizado o modelo `DummyRegressor`, configurado para realizar previsões a partir da média aritmética da variável `valor_de_venda`, calculada exclusivamente com os dados do conjunto de treino, correspondente ao período de 01/01/2024 a 24/09/2025.

   Valor obtido foi utilizado como previsão fixa para os registros dos conjuntos de validação e teste, permitindo avaliar o desempenho de uma abordagem simples, sem considerar as características individuais de cada registro.

**Avaliação das Métricas de Erro**

   Para avaliar o desempenho da baseline, foram consideradas duas métricas:

   - **MAE (Erro Médio Absoluto):** utilizado para verificar a diferença média entre os valores previstos e os preços reais dos combustíveis, em reais (R$).
   - **RMSE (Raiz do Erro Quadrático Médio):** utilizado para avaliar os erros das previsões, atribuindo maior peso às diferenças mais elevadas entre os valores previstos e observados.

**Justificativa da Baseline**

   A utilização do `DummyRegressor` permitiu estabelecer um ponto de comparação inicial para os próximos modelos. Dessa forma, será possível verificar se a aplicação de métodos mais avançados apresenta melhorias em relação à previsão baseada apenas na média histórica dos preços.

   Essa comparação também será importante para avaliar se os ganhos de desempenho justificam a utilização de modelos com maior complexidade.

**Relação com os Objetivos do Projeto**

   Para a análise voltada ao consumidor, a baseline estabelece uma referência inicial de erro para as previsões de preços, contribuindo para avaliar a precisão dos modelos que poderão auxiliar na identificação de melhores condições de abastecimento.

   No contexto da Forno Nobre, essa referência também será utilizada para avaliar a precisão das estimativas relacionadas aos custos de combustível. Considerando o impacto dessas despesas na operação de transporte, a redução dos erros de previsão poderá contribuir para um planejamento financeiro mais adequado e um melhor acompanhamento dos custos operacionais.

In [7]:
modelo_baseline = DummyRegressor(strategy='mean')

modelo_baseline.fit(X_treino, y_treino)
valor_medio_treino = modelo_baseline.constant_[0][0]

predicoes_val = modelo_baseline.predict(X_val)
predicoes_teste = modelo_baseline.predict(X_teste)

mae_val = mean_absolute_error(y_val, predicoes_val)
rmse_val = np.sqrt(mean_squared_error(y_val, predicoes_val))

mae_teste = mean_absolute_error(y_teste, predicoes_teste)
rmse_teste = np.sqrt(mean_squared_error(y_teste, predicoes_teste))

print(" REFERÊNCIA ESTABELECIDA (BASELINE)")
print("="*45)
print(f"Estratégia do Baseline: Prever sempre a média do Treino (R$ {valor_medio_treino:.2f})")
print("-" * 45)
print("Desempenho na base de VALIDAÇÃO:")
print(f"MAE  : R$ {mae_val:.4f} (Erro médio por litro)")
print(f"RMSE : R$ {rmse_val:.4f}")
print("-" * 45)
print("Desempenho na base de TESTE (Métrica Inicial Final):")
print(f"MAE  : R$ {mae_teste:.4f} (Erro médio por litro)")
print(f"RMSE : R$ {rmse_teste:.4f}")
print("=" * 45)
print(" Conclusão: Qualquer modelo de Machine Learning futuro precisará ter um MAE Menor que o valor acima para ser considerado útil.")

 REFERÊNCIA ESTABELECIDA (BASELINE)
=============================================
Estratégia do Baseline: Prever sempre a média do Treino (R$ 5.68)
---------------------------------------------
Desempenho na base de VALIDAÇÃO:
MAE  : R$ 0.7079 (Erro médio por litro)
RMSE : R$ 0.8454
---------------------------------------------
Desempenho na base de TESTE (Métrica Inicial Final):
MAE  : R$ 1.1399 (Erro médio por litro)
RMSE : R$ 1.2599
=============================================
 Conclusão: Qualquer modelo de Machine Learning futuro precisará ter um MAE Menor que o valor acima para ser considerado útil.