In [15]:
import pandas as pd
from pathlib import Path
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Visualizando os dados

In [16]:


# Se o seu notebook estiver dentro da pasta 'notebooks/', o caminho para 'bruto' volta um nível (../)
# Se estiver rodando na raiz do projeto, use Path('dados/bruto')
caminho_bruto = Path('../dados/bruto')
arquivos_csv = list(caminho_bruto.glob('*.csv'))

dfs = []
colunas_padrao = None
estruturas_compativeis = True

for arquivo in arquivos_csv:
    # Lendo cada arquivo
    df = pd.read_csv(arquivo, sep=';') # Ajuste o sep=',' ou sep=';' conforme o padrão dos seus dados
    
    # 1. Visualização mínima e informações básicas
    print(f"\nArquivo: {arquivo.name} | Formato: {df.shape[0]} linhas, {df.shape[1]} colunas")
    display(df.head(2)) # Use print(df.head(2)) se estiver usando um script .py comum em vez de Notebook
    
    # 2. Verificação de estrutura (número e nome das colunas)
    colunas_atuais = list(df.columns)
    if colunas_padrao is None:
        colunas_padrao = colunas_atuais
    elif colunas_padrao != colunas_atuais:
        estruturas_compativeis = False
        print(f"⚠️ Inconsistência encontrada no arquivo: {arquivo.name}")
        
    dfs.append(df)

# 3. Junção (Concatenação) dos arquivos
if not arquivos_csv:
    print("Nenhum arquivo CSV encontrado na pasta especificada.")
elif estruturas_compativeis:
    print("\n✅ Estruturas verificadas e idênticas. Unindo os arquivos...")
    df_unificado = pd.concat(dfs, ignore_index=True)
    
    print(f"DataFrame final criado com sucesso! Formato unificado: {df_unificado.shape}")
    display(df_unificado.head())
    
    # Exportando o arquivo final para a pasta de dados processados correspondente à sua estrutura
    # caminho_processado = Path('../dados/processado/dados_unificados.csv')
    # df_unificado.to_csv(caminho_processado, index=False)
else:
    print("\n❌ Os arquivos possuem estruturas de colunas diferentes. A junção automática foi abortada para preservar a integridade.")

Arquivo: Preços semestrais - AUTOMOTIVOS_2024.01.csv | Formato: 477154 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA

Arquivo: Preços semestrais - AUTOMOTIVOS_2024.02.csv | Formato: 421382 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA,01/07/2024,"6,79",NaN,R$ / litro,VIBRA
1,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA ADITIVADA,01/07/2024,"6,84",NaN,R$ / litro,VIBRA

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4988\3530351283.py:12: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 14: Unidade de Medida, 15: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(arquivo, sep=';') # Ajuste o sep=',' ou sep=';' conforme o padrão dos seus dados

Arquivo: Preços semestrais - AUTOMOTIVOS_2025.01.csv | Formato: 429523 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN

Arquivo: Preços semestrais - AUTOMOTIVOS_2025.02.csv | Formato: 384208 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA

Arquivo: Preços semestrais - AUTOMOTIVOS_2026.01.csv | Formato: 422418 linhas, 16 colunas

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,GASOLINA,02/01/2026,"7,97",NaN,R$ / litro,IPIRANGA
1,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,DIESEL,02/01/2026,"8,15",NaN,R$ / litro,IPIRANGA

✅ Estruturas verificadas e idênticas. Unindo os arquivos...
DataFrame final criado com sucesso! Formato unificado: (2134685, 16)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,"5,68",NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,"5,93",NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,"3,99",NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,"5,48",NaN,R$ / litro,VIBRA

In [17]:


# Assume-se que 'df_unificado' é o DataFrame resultante do passo anterior

# 1. Inspeção Geral (Dimensões e Duplicidades)
linhas, colunas = df_unificado.shape
linhas_duplicadas = df_unificado.duplicated().sum()

print("="*50)
print("🔍 INSPEÇÃO GERAL DO DATASET")
print("="*50)
print(f"Dimensões globais : {linhas} linhas e {colunas} colunas")
print(f"Linhas duplicadas : {linhas_duplicadas} ocorrencias exatas")
print("="*50 + "\n")

# 2. Construindo a tabela detalhada por coluna
inspecao = pd.DataFrame({
    'Tipo': df_unificado.dtypes,
    'Ausências (Qtd)': df_unificado.isnull().sum(),
    'Ausências (%)': (df_unificado.isnull().sum() / linhas) * 100,
    'Chaves/Únicos': df_unificado.nunique()
})

# 3. Extraindo categorias (amostra de dados reais)
amostras = []
for col in df_unificado.columns:
    # Pega até 3 valores únicos para entender as categorias preenchidas
    valores = df_unificado[col].dropna().unique()
    amostra_str = ", ".join(map(str, valores[:3]))
    if len(valores) > 3:
        amostra_str += ", ..."
    amostras.append(amostra_str)

inspecao['Categorias (Amostras)'] = amostras

# Formatando a coluna de porcentagem para melhor leitura
inspecao['Ausências (%)'] = inspecao['Ausências (%)'].round(2).astype(str) + '%'

# Ordenando para mostrar as colunas com mais ausências primeiro (opcional, útil para limpeza)
inspecao = inspecao.sort_values(by='Ausências (Qtd)', ascending=False)

# 4. Exibindo a tabela organizada
# Se estiver no Jupyter/VS Code com interface interativa, o 'display' renderiza uma tabela HTML
display(inspecao)

==================================================
🔍 INSPEÇÃO GERAL DO DATASET
==================================================
Dimensões globais : 2134685 linhas e 16 colunas
Linhas duplicadas : 9129 ocorrencias exatas
==================================================

,Tipo,Ausências (Qtd),Ausências (%),Chaves/Únicos,Categorias (Amostras)
Valor de Compra,float64,2134685,100.0%,0,
Complemento,str,1649676,77.28%,2362,"KM 70, LOTE 12 QUADRAB, L..."
Bairro,str,12807,0.6%,5511,"SANTA ESMERALDA, CENTRO, CANAFISTULA, ..."
Numero Rua,str,9367,0.44%,4158,"1901, 274, 678, ..."
Revenda,str,9114,0.43%,11558,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...
Municipio,str,9114,0.43%,461,"ARAPIRACA, RIO LARGO, VERA CRUZ, ..."
Regiao - Sigla,str,9114,0.43%,5,"NE, SE, S, ..."
Estado - Sigla,str,9114,0.43%,27,"AL, BA, MA, ..."
CNPJ da Revenda,object,9114,0.43%,20767,"02.817.655/0001-82, 12.706.529/0001-04, 01...."
Nome da Rua,str,9114,0.43%,8189,"RODOVIA AL-220, RUA SAO FRANCISCO, RODOVIA AL-..."
Produto,str,9114,0.43%,6,"GASOLINA, GASOLINA ADITIVADA, DIESEL S10, ..."
Cep,str,9114,0.43%,9862,"57312-025, 57300-080, 57302-802, ..."
Data da Coleta,str,9114,0.43%,680,"01/01/2024, 02/01/2024, 03/01/2024, ..."
Valor de Venda,str,9114,0.43%,704,"5,68, 5,93, 3,99, ..."
Unidade de Medida,str,9114,0.43%,3,"R$ / litro, R$ / m³, R$ / m3"
Bandeira,str,9114,0.43%,55,"VIBRA, BRANCA, IPIRANGA, ..."

# Tratando## Limpeza e Normalização dos Dados (`Limpar`)

Nesta etapa, aplicamos um pipeline de sanitização e padronização sobre a base de dados unificada para garantir a integridade das análises:

1. **Padronização do Nome das Colunas**:
   * Conversão de todos os nomes de colunas para o padrão *snake_case* (letras minúsculas, substituindo hífens e espaços por `_`).

2. **Remoção de Duplicidades**:
   * Eliminação de registros completamente duplicados identificados na fase de inspeção.

3. **Tratamento de Identificadores e Variáveis Financeiras**:
   * **Valores Monetários (`valor_de_venda`)**: Conversão do separador decimal de vírgula para ponto e transformação do tipo de dado para numérico (`float64`).
   * **Identificadores (`cnpj_da_revenda` e `cep`)**: Remoção de caracteres especiais (pontos, traços e barras) via expressões regulares, mantendo apenas os números literais.

4. **Padronização de Categorias e Unidades**:
   * **Unidades de Medida (`unidade_de_medida`)**: Correção de variações de grafia (substituição de `m3` por `m³`).
   * **Caixa do Texto**: Padronização de todas as colunas de texto/categorias para letras **minúsculas**.

5. **Tratamento de Datas (`data_da_coleta`)**:
   * Conversão para formato de data nativo e remoção da exibição do horário (`00:00:00`).
   * Preservação do tipo temporal em valores ausentes através do marcador nativo `NaT` (*Not a Time*).

6. **Tratamento de Valores Ausentes (Nulos)**:
   * **Colunas Numéricas**: Preenchimento de nulos com `0` (aplicado à coluna `valor_de_compra`).
   * **Colunas de Texto**: Preenchimento de nulos com o rótulo `"não consta"`.

In [18]:
# 1. Padronizar nomes das colunas
df_unificado.columns = (
    df_unificado.columns
    .str.lower()
    .str.replace(' - ', '_')
    .str.replace(' ', '_')
)

# 2. Remover linhas duplicadas
df_unificado = df_unificado.drop_duplicates()

# 3. Normalizações de Identificadores e Finanças
# a) Valor de Venda
if 'valor_de_venda' in df_unificado.columns:
    df_unificado['valor_de_venda'] = df_unificado['valor_de_venda'].astype(str).str.replace(',', '.')
    df_unificado['valor_de_venda'] = pd.to_numeric(df_unificado['valor_de_venda'], errors='coerce')

# b) CNPJ e CEP: Remoção de qualquer caractere não numérico
if 'cnpj_da_revenda' in df_unificado.columns:
    df_unificado['cnpj_da_revenda'] = df_unificado['cnpj_da_revenda'].astype(str).str.replace(r'\D', '', regex=True)
    df_unificado['cnpj_da_revenda'] = df_unificado['cnpj_da_revenda'].replace(['nan', ''], np.nan)

if 'cep' in df_unificado.columns:
    df_unificado['cep'] = df_unificado['cep'].astype(str).str.replace(r'\D', '', regex=True)
    df_unificado['cep'] = df_unificado['cep'].replace(['nan', ''], np.nan)

# c) Unidade de Medida
if 'unidade_de_medida' in df_unificado.columns:
    df_unificado['unidade_de_medida'] = (
        df_unificado['unidade_de_medida']
        .astype(str)
        .str.replace('m3', 'm³')
        .replace('nan', np.nan)
    )

# d) Datas: Tratamento com NaT para nulos e remoção das horas
if 'data_da_coleta' in df_unificado.columns:
    df_unificado['data_da_coleta'] = pd.to_datetime(df_unificado['data_da_coleta'], format='%d/%m/%Y', errors='coerce')
    df_unificado['data_da_coleta'] = df_unificado['data_da_coleta'].dt.date

# 4. Tratamento de Nulos e Padronização de Textos
colunas_numericas = df_unificado.select_dtypes(include=['float64', 'int64']).columns
colunas_texto = df_unificado.select_dtypes(include=['object', 'string']).columns

# Numéricos: preenche com 0
df_unificado[colunas_numericas] = df_unificado[colunas_numericas].fillna(0)

# Textos: preenche nulos com "não consta" e converte tudo para letras minúsculas
for col in colunas_texto:
    if col == 'data_da_coleta':
        continue
        
    df_unificado[col] = df_unificado[col].fillna("não consta")
    df_unificado[col] = df_unificado[col].astype(str).str.lower()

# 5. Validação final
print("✅ Limpeza concluída: datas, textos em minúsculas e CEP tratados!")
print(f"Novas dimensões após limpeza: {df_unificado.shape[0]} linhas e {df_unificado.shape[1]} colunas")
display(df_unificado.head())

✅ Limpeza concluída: datas, textos em minúsculas e CEP tratados!
Novas dimensões após limpeza: 2125556 linhas e 16 colunas

,regiao_sigla,estado_sigla,municipio,revenda,cnpj_da_revenda,nome_da_rua,numero_rua,complemento,bairro,cep,produto,data_da_coleta,valor_de_venda,valor_de_compra,unidade_de_medida,bandeira
0,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,gasolina,2024-01-01,5.68,0.0,r$ / litro,vibra
1,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,gasolina aditivada,2024-01-01,5.68,0.0,r$ / litro,vibra
2,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,diesel s10,2024-01-01,5.93,0.0,r$ / litro,vibra
3,ne,al,arapiraca,comercial de combustiveis e lubrificantes vita...,02817655000182,rodovia al-220,1901,não consta,santa esmeralda,57312025,etanol,2024-01-01,3.99,0.0,r$ / litro,vibra
4,ne,al,arapiraca,auto posto sao francisco ltda,12706529000104,rua sao francisco,274,não consta,centro,57300080,gasolina,2024-01-01,5.48,0.0,r$ / litro,vibra

## 5. Transformação dos Dados (`Transformar`)

Nesta etapa, o objetivo foi preparar a base limpa para análises avançadas, criando novas dimensões de inteligência (Feature Engineering) e construindo visões macro[cite: 7].

### Justificativa das Transformações:

*   **Filtragem de Consistência**: Foram removidos os registros cujo `valor_de_venda` era igual ou inferior a zero. Preços zerados representam anomalias ou falhas de coleta e distorceriam as métricas estatísticas globais.
*   **`ano_coleta` e `mes_coleta`**: Extraídas a partir da data de coleta[cite: 7]. **Por que?** Facilitam agrupamentos de sazonalidade, análises de inflação e plotagem de gráficos temporais, eliminando o excesso de granularidade de analisar dia a dia.
*   **`tipo_bandeira`**: Classifica os postos de forma binária em 'independente' (bandeiras brancas) e 'rede_franqueada'[cite: 7]. **Por que?** Simplifica análises de modelo de negócio e competitividade. Em vez de cruzar dezenas de marcas locais, avalia-se rapidamente se corporações cobram sistematicamente mais caro do que postos de bairro.
*   **`faixa_de_preco`**: Variável que discretiza o preço de venda contínuo dividindo-o em categorias de quartis ('baixo', 'médio', 'alto')[cite: 7]. **Por que?** Útil para segmentação de mercado e mapeamento (ex: identificar quais regiões concentram postos de faixa 'alta'). Também facilita a implementação de modelos preditivos de classificação futuramente.
*   **Visão Agregada (Resumo Estatístico)**: Um novo subconjunto sumarizando preços (média, mediana, máximo e mínimo) e contagem de postos únicos (`quantidade_revendas_distintas`) por Estado e Produto[cite: 7]. **Por que?** Como a base principal possui mais de 2 milhões de registros[cite: 7], consultas contínuas tornam-se pesadas. O agrupamento atua como um *Data Mart*, ideal para análises ágeis e para alimentar *dashboards* de Business Intelligence sem lentidão.

In [19]:
# Criamos uma cópia para não alterar o dataframe da etapa anterior inadvertidamente
df_transformado = df_unificado.copy()

# ==========================================
# 1. FILTRAR
# ==========================================
# Remover possíveis registros onde o valor de venda seja 0 ou menor, pois não fazem sentido para análise de preços
df_transformado = df_transformado[df_transformado['valor_de_venda'] > 0]

# ==========================================
# 2. CRIAR VARIÁVEIS DERIVADAS
# ==========================================
# a) Variáveis temporais (Ano e Mês) a partir da data de coleta
# Como a data está em formato 'date', passamos para datetime temporariamente para extrair os atributos
datas_datetime = pd.to_datetime(df_transformado['data_da_coleta'], errors='coerce')
df_transformado['ano_coleta'] = datas_datetime.dt.year
df_transformado['mes_coleta'] = datas_datetime.dt.month

# b) Classificação da Bandeira (Independente vs Franqueada)
# Postos com bandeira "branca" são independentes. Os demais (Vibra, Ipiranga, Raízen) são de rede/franqueados.
df_transformado['tipo_bandeira'] = np.where(
    df_transformado['bandeira'] == 'branca', 
    'independente', 
    'rede_franqueada'
)

# c) Faixa de Preço (Discretização/Categorização)
# Cria 3 categorias de preço baseadas nos quartis do valor de venda
df_transformado['faixa_de_preco'] = pd.qcut(
    df_transformado['valor_de_venda'], 
    q=3, 
    labels=['baixo', 'médio', 'alto'], 
    duplicates='drop'
)

# ==========================================
# 3. AGREGAR (Criação de um Data Mart / Visão Analítica)
# ==========================================
# Vamos criar um DataFrame secundário sumarizando os preços por Estado e Produto
df_agregado = (
    df_transformado
    .groupby(['estado_sigla', 'produto'])
    .agg(
        preco_medio=('valor_de_venda', 'mean'),
        preco_mediano=('valor_de_venda', 'median'),
        preco_maximo=('valor_de_venda', 'max'),
        preco_minimo=('valor_de_venda', 'min'),
        quantidade_revendas_distintas=('cnpj_da_revenda', 'nunique') # Conta postos únicos
    )
    .reset_index()
)

# Arredondando os valores agregados para 2 casas decimais
colunas_moeda = ['preco_medio', 'preco_mediano', 'preco_maximo', 'preco_minimo']
df_agregado[colunas_moeda] = df_agregado[colunas_moeda].round(2)

# ==========================================
# VALIDAÇÃO DA TRANSFORMAÇÃO
# ==========================================
print("✅ Transformações aplicadas com sucesso!")
print(f"Dimensões do dataset principal transformado: {df_transformado.shape}")
print("\n--- Amostra das novas variáveis derivadas ---")
display(df_transformado[['data_da_coleta', 'ano_coleta', 'mes_coleta', 'bandeira', 'tipo_bandeira', 'valor_de_venda', 'faixa_de_preco']].head())

print("\n--- Visão Agregada (Média de Preços por Estado e Produto) ---")
display(df_agregado.head())

# Define o caminho de salvamento na estrutura do projeto
caminho_salvamento = Path('../dados/processado/base_anp_transformada.csv')

# Garante que a pasta exista (caso você não tenha criado manualmente)
caminho_salvamento.parent.mkdir(parents=True, exist_ok=True)

# Exporta o DataFrame final limpo e transformado
# index=False evita que os números das linhas sejam salvos como uma coluna inútil
df_transformado.to_csv(caminho_salvamento, index=False, sep=',')

print(f"✅ Arquivo salvo com sucesso em: {caminho_salvamento}")

✅ Transformações aplicadas com sucesso!
Dimensões do dataset principal transformado: (2125555, 20)

--- Amostra das novas variáveis derivadas ---

,data_da_coleta,ano_coleta,mes_coleta,bandeira,tipo_bandeira,valor_de_venda,faixa_de_preco
0,2024-01-01,2024,1,vibra,rede_franqueada,5.68,baixo
1,2024-01-01,2024,1,vibra,rede_franqueada,5.68,baixo
2,2024-01-01,2024,1,vibra,rede_franqueada,5.93,médio
3,2024-01-01,2024,1,vibra,rede_franqueada,3.99,baixo
4,2024-01-01,2024,1,vibra,rede_franqueada,5.48,baixo

--- Visão Agregada (Média de Preços por Estado e Produto) ---

,estado_sigla,produto,preco_medio,preco_mediano,preco_maximo,preco_minimo,quantidade_revendas_distintas
0,ac,diesel,7.58,7.55,8.77,6.79,47
1,ac,diesel s10,7.64,7.65,9.27,6.89,46
2,ac,etanol,5.24,5.24,7.44,4.49,32
3,ac,gasolina,7.39,7.39,8.50,6.49,51
4,ac,gasolina aditivada,7.44,7.45,8.59,6.51,47

✅ Arquivo salvo com sucesso em: ..\dados\processado\base_anp_transformada.csv

## 7. Particionamento dos Dados (`Particionar`)

Nesta etapa, o dataset foi dividido em três subconjuntos (Treino, Validação e Teste) respeitando rigorosamente a premissa do **uso real** para dados que dependem do tempo.

### O que será feito:
A base de dados foi ordenada de forma cronológica e dividida sequencialmente, desativando o embaralhamento aleatório (`shuffle=False`). O resultado exato da divisão foi:
* **Treino (70%)**: Conjunto contendo 1.487.888 linhas[cite: 8], abrangendo o período histórico mais antigo, de 01/01/2024 até 24/09/2025[cite: 8].
* **Validação (15%)**: Conjunto contendo 318.833 linhas[cite: 8], abrangendo o período intermediário de 24/09/2025 até 16/02/2026[cite: 8].
* **Teste (15%)**: Conjunto contendo 318.834 linhas[cite: 8], abrangendo o período mais recente, de 16/02/2026 até 30/06/2026[cite: 8].

### Por que foi feito:
* **Prevenção de Vazamento de Dados (*Data Leakage*)**: Como os preços dos combustíveis sofrem inflação e sazonalidade ao longo do tempo, um particionamento aleatório misturaria passado e futuro. Isso faria o modelo "espiar" as tendências de 2026 para prever os preços de 2024, invalidando o seu uso no mundo real. A abordagem cronológica (*Out-of-Time Validation*) garante que o passado preveja o futuro.
* **Propósito de cada partição**:
  * O **Treino** é utilizado exclusivamente para o modelo aprender os padrões.
  * A **Validação** é usada para testar o modelo durante a criação, permitindo ajustar os hiperparâmetros sem tocar nos dados finais.
  * O **Teste** atua como uma simulação fiel da entrada em produção, avaliando a capacidade do modelo de generalizar e fazer predições no período mais recente (fevereiro a junho de 2026)[cite: 8] que ele nunca viu antes.

In [20]:
# 1. Preparação: Ordenar os dados cronologicamente
# Isso é essencial para simular o "uso real" em dados que dependem do tempo
df_modelagem = df_transformado.sort_values(by='data_da_coleta').reset_index(drop=True)

# 2. Definir as Features (X) e a Variável Alvo/Target (y)
# Assumindo que o objetivo seja prever o preço do combustível ('valor_de_venda')
X = df_modelagem.drop(columns=['valor_de_venda'])
y = df_modelagem['valor_de_venda']

# 3. Particionamento Out-of-Time (Cronológico)
# shuffle=False é o segredo aqui: impede que os dados sejam misturados aleatoriamente,
# garantindo que o Treino pegue os dados mais antigos e o Teste os mais novos.

# Primeira divisão: 70% Treino e 30% para o restante (Validação + Teste)
X_treino, X_temp, y_treino, y_temp = train_test_split(
    X, y, 
    test_size=0.30, 
    shuffle=False 
)

# Segunda divisão: Pegamos os 30% restantes e dividimos na metade (15% Validação, 15% Teste)
X_val, X_teste, y_val, y_teste = train_test_split(
    X_temp, y_temp, 
    test_size=0.50, 
    shuffle=False
)

# ==========================================
# VALIDAÇÃO DO PARTICIONAMENTO
# ==========================================
print("✅ Particionamento cronológico concluído com sucesso!")
print(f"Treino (70%)    : {X_treino.shape[0]} linhas")
print(f"Validação (15%) : {X_val.shape[0]} linhas")
print(f"Teste (15%)     : {X_teste.shape[0]} linhas")

# Comprovando que as datas não se misturaram (Uso Real)
print("\n--- Verificação Temporal ---")
print(f"Treino    : de {X_treino['data_da_coleta'].min()} até {X_treino['data_da_coleta'].max()}")
print(f"Validação : de {X_val['data_da_coleta'].min()} até {X_val['data_da_coleta'].max()}")
print(f"Teste     : de {X_teste['data_da_coleta'].min()} até {X_teste['data_da_coleta'].max()}")

✅ Particionamento cronológico concluído com sucesso!
Treino (70%)    : 1487888 linhas
Validação (15%) : 318833 linhas
Teste (15%)     : 318834 linhas

--- Verificação Temporal ---
Treino    : de 2024-01-01 até 2025-09-24
Validação : de 2025-09-24 até 2026-02-16
Teste     : de 2026-02-16 até 2026-06-30

## 8. Referenciar (`Baseline e Métrica Inicial`)

Nesta etapa final do fluxo mínimo de trabalho, estabelecemos a métrica de referência (Baseline) do projeto[cite: 1]. Essa referência atua como uma linha de corte obrigatória: qualquer modelo de Machine Learning (como XGBoost, Random Forest ou modelos de séries temporais) que for testado no futuro precisará, obrigatoriamente, superar o desempenho dessa solução ingênua para ser considerado útil.

---

### O que foi feito

1. **Construção do Modelo Incondicional (Dummy Regressor)**:
   * Criamos um modelo ingênuo configurado para calcular a **média aritmética** da variável alvo (`valor_de_venda`) com base exclusiva no conjunto de **Treino** (período de 01/01/2024 a 24/09/2025)[cite: 8].
   * Esse valor fixo obtido no treino foi utilizado como palpite cego para prever o preço de todas as linhas dos conjuntos de **Validação** e **Teste**[cite: 8].

2. **Cálculo das Métricas de Erro**:
   * **MAE (Mean Absolute Error / Erro Médio Absoluto)**: Mede o desvio médio das previsões em Reais (R$) diretamente por litro de combustível, oferecendo uma leitura clara e interpretável do erro em escala financeira real.
   * **RMSE (Root Mean Squared Error / Raiz do Erro Quadrático Médio)**: Penaliza desvios maiores e discrepantes de preço (outliers), servindo para avaliar a estabilidade do chute em momentos de forte variação de mercado.

---

### Por que foi feito

* **Definição de Linha de Corte (Ponto de Partida)**:
  Nenhum modelo preditivo deve ser avaliado no vácuo. Se a média histórica simples conseguir errar, por exemplo, R$ 0,15 por litro na base de teste, um modelo preditivo complexo só justificará seu custo computacional e de implementação se conseguir entregar um erro significativamente inferior a esse patamar.

* **Conexão com os Objetivos do Projeto**:
  * **Para o Consumidor Geral**: Define o limite do quão precisa pode ser a sinalização de "quando e onde" vale a pena abastecer.
  * **Para a Operação da Forno Nobre**: Serve como benchmark financeiro. Qualquer desvio preditivo na compra de grande volume de combustível representa impacto direto na margem de frete; portanto, o baseline fixa a margem de erro mínima a ser superada na gestão de suprimentos.

In [21]:
# 1. Criar o modelo Baseline
# A estratégia 'mean' significa que o modelo vai calcular a média do y_treino 
# e usar esse valor exato para todas as previsões futuras.
modelo_baseline = DummyRegressor(strategy='mean')

# "Treinar" o baseline (ele apenas calcula a média aritmética do treino)
modelo_baseline.fit(X_treino, y_treino)
valor_medio_treino = modelo_baseline.constant_[0][0]

# 2. Realizar as predições nas bases cegas (Validação e Teste)
predicoes_val = modelo_baseline.predict(X_val)
predicoes_teste = modelo_baseline.predict(X_teste)

# 3. Calcular as métricas de erro (MAE e RMSE)
# MAE (Mean Absolute Error): Erro médio absoluto em Reais (R$)
# RMSE (Root Mean Squared Error): Penaliza erros grandes/discrepantes
mae_val = mean_absolute_error(y_val, predicoes_val)
rmse_val = np.sqrt(mean_squared_error(y_val, predicoes_val))

mae_teste = mean_absolute_error(y_teste, predicoes_teste)
rmse_teste = np.sqrt(mean_squared_error(y_teste, predicoes_teste))

# ==========================================
# REGISTRO DA MÉTRICA INICIAL
# ==========================================
print("🎯 REFERÊNCIA ESTABELECIDA (BASELINE)")
print("="*45)
print(f"Estratégia do Baseline: Prever sempre a média do Treino (R$ {valor_medio_treino:.2f})")
print("-" * 45)
print("Desempenho na base de VALIDAÇÃO:")
print(f"MAE  : R$ {mae_val:.4f} (Erro médio por litro)")
print(f"RMSE : R$ {rmse_val:.4f}")
print("-" * 45)
print("Desempenho na base de TESTE (Métrica Inicial Final):")
print(f"MAE  : R$ {mae_teste:.4f} (Erro médio por litro)")
print(f"RMSE : R$ {rmse_teste:.4f}")
print("=" * 45)
print("💡 Conclusão: Qualquer modelo de Machine Learning futuro precisará ter um MAE Menor que o valor acima para ser considerado útil.")

🎯 REFERÊNCIA ESTABELECIDA (BASELINE)
=============================================
Estratégia do Baseline: Prever sempre a média do Treino (R$ 5.68)
---------------------------------------------
Desempenho na base de VALIDAÇÃO:
MAE  : R$ 0.7079 (Erro médio por litro)
RMSE : R$ 0.8454
---------------------------------------------
Desempenho na base de TESTE (Métrica Inicial Final):
MAE  : R$ 1.1399 (Erro médio por litro)
RMSE : R$ 1.2599
=============================================
💡 Conclusão: Qualquer modelo de Machine Learning futuro precisará ter um MAE Menor que o valor acima para ser considerado útil.